apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-app
  namespace: woven-grail-428923-b2
spec:
  template:
    spec:
      containers:
        - image: gcr.io/woven-grail-428923-b2/flask-app:latest
          resources:
            limits:
              memory: "32Gi"
              cpu: "8"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3